server:
  port: 9090
spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
#      mode: always
      data-locations: classpath:data.sql
security:
  jwt:
    secret-key: kicchi