app:
  local-url: http://localhost:${server.port}
server:
  port: 9090
spring:
  application:
    name: ticketing-project-rest
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
#      mode: always
      data-locations: classpath:data.sql
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: akarako@gmail.com
    password: akarakao2020
security:
  jwt:
    secret-key: kicchi
springdoc:
  swagger-ui:
    path: /swagger-ui.html